version: '3.3'
services:
  mongo_db:
    image: mongo:3.2
    volumes:
      - post_db:/data/db
    networks:
      - reddit
      # - back_net
  ui:
    build: ./ui
    image: ${USERNAME}/ui:${VERSION_UI}
    ports:
      - ${PORT}:${PORT}/tcp
    networks:
      - reddit
      # - front_net


  post:
    build: ./post-py
    image: ${USERNAME}/post:${VERSION_POST}
    networks:
      - reddit
      # - back_net
      # - front_net

  comment:
    build: ./comment
    image: ${USERNAME}/comment:${VERSION_COMMENT}
    networks:
      - reddit
      # - back_net
      # - front_net

volumes:
  post_db:

networks:
  reddit:
  back_net:
  front_net:
